title: meteor-application-template-react
description: A template for quickly starting Meteor application development
google_analytics:
show_downloads: true
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gems:
  - jekyll-mentions
